---
title: "HomeWork Assignment 1"
author: "Rohan Chitale (23206793)"
format: html
editor: visual
---

# Reading the dataset

```{r}
# Load necessary libraries
library(tidyverse)
library(skimr)
library(ggplot2)
```

```{r}
data=read_csv('Sleep_Efficiency.csv')

```

```{r}
head(data)
```

```{r}
summary(data)
```

```{r}
# Check for missing values
sum(is.na(data))
```

```{r}
# Distributions of all variables
data %>% select(Age,`Sleep duration`,`Sleep efficiency`,`REM sleep percentage`, `Deep sleep percentage`,`Light sleep percentage`,Awakenings,`Caffeine consumption`,`Alcohol consumption`,`Exercise frequency`) %>% gather(key="variable",value= "value")%>%ggplot(aes(x=value))+geom_histogram(bins=30,fill='blue',alpha=0.7)+facet_wrap(~variable,scales='free')+theme_minimal() +
  labs(title='Distribution of Numerical Variables')
```

```{r}
# Count of Categorical varaibles
data%>%select(Gender,`Smoking status`)%>% gather(key="variable",value="value")%>% 
ggplot(aes(x=value))+geom_bar(fill='blue',alpha=0.7)+facet_wrap(~variable,scales ='free')+theme_minimal()+labs(title='Count of Categorical Variables')
```

```{r}
# Print Correlation Matrix
correlationmatrix=data %>%select(Age,`Sleep duration`,`Sleep efficiency`,`REM sleep percentage`,`Deep sleep percentage`,`Light sleep percentage`,Awakenings,`Caffeine consumption`,`Alcohol consumption`,`Exercise frequency`) %>%cor()
print(correlationmatrix)
```
